### ISSUE TITLE
Can't open on MacOS with non-Apple JRE

### ISSUE THREAD

**Issue by jeremybrooks** [jeremybrooks/readsy-desktop#1]
`java.lang.NoClassDefFoundError: com/apple/eawt/AboutHandler
	at net.jeremybrooks.readsy.Readsy.main(Readsy.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:81)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:53)
Caused by: java.lang.ClassNotFoundException: com.apple.eawt.AboutHandler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:604)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 7 more
`

https://stackoverflow.com/questions/42818440/catching-java-lang-noclassdeffounderror-on-non-macos-jre

**Comment by jeremybrooks** [comment]
Fixed in develop branch with commit https://github.com/jeremybrooks/readsy-desktop/commit/e13359b94e3f8ce4632293b5051671f4f5baa1e0
